name:                battleship
version:             0.1.0.0
github:              "vipo/battleship"
license:             BSD3
author:              "Viaceslav Pozdniakov"
maintainer:          "pi@homedir.eu"
copyright:           "2018 Viaceslav Pozdniakov"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/vipo/battleship#readme>

data-files:
- static/*.html

dependencies:
- base >= 4.7 && < 5
- aeson
- bencoding
- bytestring
- http-api-data
- http-media
- servant
- servant-server
- scientific
- string-conversions
- text
- text-show
- unordered-containers
- vector

library:
  source-dirs: src

executables:
  battleship:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - battleship
    - random
    - text
    - wai
    - warp

tests:
  battleship-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - battleship
    - tasty
    - tasty-hunit
    - tasty-quickcheck
