name:                battleship
version:             0.1.0.0
github:              "vipo/battleship"
license:             BSD3
author:              "Viaceslav Pozdniakov"
maintainer:          "pi@homedir.eu"
copyright:           "2018 Viaceslav Pozdniakov"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/vipo/battleship#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- scientific
- text-show

library:
  source-dirs: src

executables:
  battleship:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - battleship
    - http-api-data
    - random
    - servant
    - servant-server
    - text
    - wai
    - warp

tests:
  battleship-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - battleship
